/* PROJECT: POMPR-PRO | VERSION: V5.8-DATA | STATUS: MODULAR REEL 1 (60 CHARS) */

export const libraryData = {
  genres: ["CORPORATE", "UGC LIFESTYLE", "AD STUDIO", "EDITORIAL LUXURY", "CYBER STARTUP", "DESIGN ASSET"],
  interaction_verbs: ["Interviewing", "Engaged in Dialogue", "Confronting", "Collaborating", "Shadowing", "Ignoring", "Instructing", "Sparring", "Grappling", "Blocking the Shot"],
  platforms: ["NANO BANANA PRO", "MIDJOURNEY V7", "SORA REEL ENGINE", "DALL-E 4"],
  actions: [
    { id: "act_01", type: "S", label: "Hitting the Mark", desc: "caught in a perfectly neutral ready-position, eyes focused" },
    { id: "act_02", type: "S", label: "Power Stance", desc: "hands on hips, chin tilted for hero-lighting" },
    { id: "act_03", type: "V", label: "Entering Frame", desc: "walking into focus from the side of the lens" },
    { id: "act_04", type: "V", label: "Slingshot Forward", desc: "surging forward with intense momentum" },
    { id: "act_05", type: "U", label: "Finding Light", desc: "tilting chin up to catch cinematic rim-lighting" },
    { id: "act_06", type: "U", label: "Pulling Focus", desc: "intense gaze shifting slowly toward the lens" },
    { id: "act_07", type: "V", label: "Fork Dive", desc: "suspension compressing deep, perfectly controlled" }
  ],
  scenes: [
    { id: "sc_01", genre: "CORPORATE", label: "6AM News Desk", desc: "Interior broadcast studio, blue panels", lighting: "Balanced high-key", lens: "35mm", triggers: ["plexiglass reflections", "walnut grain"] },
    { id: "sc_02", genre: "AD STUDIO", label: "Critical Moment OR", desc: "Surgical theater, sterile blue drapes", lighting: "Spotlights", lens: "50mm Macro", triggers: ["nitrile sheen"] },
    { id: "sc_03", genre: "UGC LIFESTYLE", label: "Golden Hour Driveway", desc: "Suburban exterior, manicured lawn", lighting: "Warm backlight", lens: "85mm", triggers: ["dust motes"] },
    { id: "sc_04", genre: "EDITORIAL LUXURY", label: "Art Deco Hall", desc: "Spiral staircase, geometric tile", lighting: "Dramatic curves", lens: "28mm", triggers: ["crystal refraction"] },
    { id: "sc_05", genre: "CYBER STARTUP", label: "Neon Command", desc: "Holographic terminals, steam rising", lighting: "Bi-color Neon", lens: "24mm", triggers: ["glitch artifacts"] },
    { id: "sc_06", genre: "CORPORATE", label: "Glass Atrium", desc: "Corporate lobby, floor-to-ceiling glass", lighting: "Natural High-Key", lens: "35mm", triggers: ["transparency"] },
    { id: "sc_07", genre: "UGC LIFESTYLE", label: "Urban Noir Loft", desc: "Brick walls, grimy windows", lighting: "Volumetric shafts", lens: "35mm", triggers: ["Tyndall effect"] },
    { id: "sc_08", genre: "CYBER STARTUP", label: "Orbital Crew Quarters", desc: "Sleek composite panels, viewport curvature", lighting: "Cool LED", lens: "18mm", triggers: ["HUD glow"] },
    { id: "sc_09", genre: "AD STUDIO", label: "Logistics Hub", desc: "Industrial warehouse, metal shelving", lighting: "Fluorescent teal tint", lens: "24mm", triggers: ["metallic sheen"] },
    { id: "sc_10", genre: "DESIGN ASSET", label: "Minimalist Grid", desc: "Infinite white void, 3D grid", lighting: "Flat ambient", lens: "50mm", triggers: ["vector clarity"] },
    { id: "sc_11", genre: "EDITORIAL LUXURY", label: "Modern Zen Bedroom", desc: "Ribbed wood slats, marble accents", lighting: "Soft indirect LED", lens: "24mm", triggers: ["material contrast"] },
    { id: "sc_12", genre: "EDITORIAL LUXURY", label: "Art Deco Salon", desc: "Ornate ceiling, dark wood paneling", lighting: "Warm ambient", lens: "35mm", triggers: ["ornamental detailing"] },
    { id: "sc_13", genre: "UGC LIFESTYLE", label: "Industrial Loft Studio", desc: "Exposed brick, factory windows", lighting: "Natural daylight", lens: "24mm", triggers: ["surface imperfections"] },
    { id: "sc_14", genre: "EDITORIAL LUXURY", label: "Industrial Luxe Loft", desc: "Double-height loft, red brick, leather", lighting: "Warm pendant bulbs", lens: "35mm", triggers: ["leather patina"] },
    { id: "sc_15", genre: "UGC LIFESTYLE", label: "Urban Noir Hideaway", desc: "Converted warehouse loft", lighting: "Low-key, hard side-light", lens: "35mm", triggers: ["dust motes"] },
    { id: "sc_16", genre: "AD STUDIO", label: "Abandoned Warehouse", desc: "Cracked concrete, industrial decay", lighting: "Diagonal beam light", lens: "35mm", triggers: ["moisture puddles"] },
    { id: "sc_17", genre: "CYBER STARTUP", label: "Futuristic Transit Tunnel", desc: "Cylindrical passage, structural ribs", lighting: "Continuous linear LED", lens: "18mm", triggers: ["infinite symmetry"] },
    { id: "sc_18", genre: "UGC LIFESTYLE", label: "Jungle Waterfall", desc: "Tropical foliage, secluded clearing", lighting: "Natural backlighting", lens: "35mm", triggers: ["mist particulate"] },
    { id: "sc_19", genre: "AD STUDIO", label: "Precision Surgical Suite", desc: "State-of-the-art sterile OR", lighting: "Shadow-minimized clinical", lens: "28mm Wide", triggers: ["articulated arms"] },
    { id: "sc_20", genre: "CORPORATE", label: "Tech Startup Lab", desc: "Black lab tables, glass equipment", lighting: "High-spec clean-room", lens: "35mm", triggers: ["metal snaps"] }
  ],
  characters: [
    { id: "none", genre: "ALL", name: "[ NO ACTOR - B-ROLL ]", details: "Environment focus", outfit: "N/A", textures: ["ambient depth"] },
    { id: "ch_01", genre: "CORPORATE", name: "Anchorwoman", details: "Mid-30s, square face, red lipstick", outfit: "Red dress, Rolex watch", textures: ["skin-pores", "fabric weave"] },
    { id: "ch_02", genre: "UGC LIFESTYLE", name: "Senior Raymond", details: "80s, Roman nose, grey mustache", outfit: "Yellow windbreaker, beanie", textures: ["leathery skin", "salt-crust"] },
    { id: "ch_03", genre: "CYBER STARTUP", name: "Radiation Mutant", details: "Blistered skin, yellow eyes, tumors", outfit: "Disintegrating jumpsuit, fused welding mask", textures: ["MONA tattoo", "toxic blisters"] },
    { id: "ch_04", genre: "EDITORIAL LUXURY", name: "The Invisible Icon", details: "Hollow form, negative space", outfit: "Charcoal suit, fedora", textures: ["bespoke wool", "translucency"] },
    { id: "ch_05", genre: "AD STUDIO", name: "Microsurgeon (Male)", details: "Mid-40s, sharp eyes, surgical cap", outfit: "Teal scrubs, latex gloves", textures: ["manicured hands"] },
    { id: "ch_06", genre: "UGC LIFESTYLE", name: "Teen Skater Boy", details: "17, lanky, light skin, curls, blue eyes, light acne", outfit: "Graphic tee, flannel shirt, baggy shorts", textures: ["angel-wings decal", "silicon bracelets"] },
    { id: "ch_07", genre: "AD STUDIO", name: "Veteran Lineman", details: "Late 50s, sun-damaged skin, walrus mustache", outfit: "Orange jacket, hard hat", textures: ["Unit 402 marking"] },
    { id: "ch_08", genre: "EDITORIAL LUXURY", name: "Runway Model", details: "Tall, black straight hair", outfit: "Couture gown", textures: ["high-gloss skin"] },
    { id: "ch_09", genre: "AD STUDIO", name: "Golden Retriever", details: "Glossy fur, intelligent eyes", outfit: "Leather collar", textures: ["wet nose"] },
    { id: "ch_10", genre: "CYBER STARTUP", name: "Android Companion", details: "Symmetrical sheen, internal glow", outfit: "Metallic jumpsuit", textures: ["uncanny skin"] },
    { id: "ch_11", genre: "CORPORATE", name: "Tech CEO", details: "Voluptuous, sleek hair, piercing eyes", outfit: "Blue tweed blazer, little black dress", textures: ["silver jewelry"] },
    { id: "ch_12", genre: "UGC LIFESTYLE", name: "Retired Detective", details: "60s, salt-and-pepper, square face", outfit: "Tan trench coat, rumpled shirt", textures: ["5 o'clock shadow"] },
    { id: "ch_13", genre: "AD STUDIO", name: "Forensic Investigator (F)", details: "30s, alert, ponytail, round face", outfit: "Tactical vest, cargo pants", textures: ["nylon texture"] },
    { id: "ch_14", genre: "CYBER STARTUP", name: "Cybernetic Engineer", details: "35, rectangular face, muscular, augmented", outfit: "Utility jumpsuit with nodes", textures: ["scalp ports"] },
    { id: "ch_15", genre: "EDITORIAL LUXURY", name: "Runway Plus-Size Icon", details: "Full-figured, statuesque, radiant", outfit: "Geometric silk dress", textures: ["radiant skin"] },
    { id: "ch_16", genre: "DESIGN ASSET", name: "Minimalist Coder (3D)", details: "Simplified figure, circular spectacles", outfit: "Oversized Digital Teal hoodie", textures: ["matte plastic"] },
    { id: "ch_17", genre: "DESIGN ASSET", name: "Isometric Surgeon", details: "Stylized, elongated limbs", outfit: "Solid color OR scrubs", textures: ["flat vector"] },
    { id: "ch_18", genre: "AD STUDIO", name: "Deep-Sea Tech Diver", details: "Late 20s, Kirby Morgan helmet", outfit: "Black-and-silver composite suit", textures: ["LED bloom"] },
    { id: "ch_19", genre: "CORPORATE", name: "Finance Analyst", details: "50s,blonde bun, pink frame glasses", outfit: "White lace shirt", textures: ["lace detail"] },
    { id: "ch_20", genre: "UGC LIFESTYLE", name: "Grandma Baker", details: "70s, rosy-cheeked, grey hair", outfit: "Floral blouse, white apron", textures: ["flour dust"] },
    { id: "ch_21", genre: "AD STUDIO", name: "Delivery Driver", details: "Male, square face, beard stubble", outfit: "Gray warehouse shirt, cargo shorts", textures: ["handheld scanner"] },
    { id: "ch_22", genre: "AD STUDIO", name: "Roofer", details: "Male, oblong face, sunburnt skin", outfit: "Faded cotton T-shirt, tool belt", textures: ["crow's feet"] },
    { id: "ch_23", genre: "AD STUDIO", name: "Plumber", details: "Male, round face, ruddy cheeks", outfit: "Blue cotton coveralls, baseball cap", textures: ["worn knees"] },
    { id: "ch_24", genre: "AD STUDIO", name: "Landscaper", details: "Male, triangular face, black ponytail", outfit: "Green uniform shirt, cargo pants", textures: ["grass stains"] },
    { id: "ch_25", genre: "AD STUDIO", name: "Warehouse Worker (F)", details: "Square face, muscular, powerful stance", outfit: "Neon safety vest", textures: ["forearm scar"] },
    { id: "ch_26", genre: "AD STUDIO", name: "Electrician", details: "Male, square face, sandy-blond hair", outfit: "Navy work shirt, reflective strips", textures: ["chin scar"] },
    { id: "ch_27", genre: "AD STUDIO", name: "Painter", details: "Male, round face, paint-speckled skin", outfit: "White overalls, tool belt", textures: ["plaster dust"] },
    { id: "ch_28", genre: "AD STUDIO", name: "Farmer", details: "Male, round face, sun-weathered", outfit: "Plaid cotton shirt, denim overalls", textures: ["muddy boots"] },
    { id: "ch_29", genre: "AD STUDIO", name: "Welder", details: "Male, oblong face, angular jawline", outfit: "Heavy leather apron, mask", textures: ["burn scar near temple"] },
    { id: "ch_30", genre: "UGC LIFESTYLE", name: "Bookish Student (F)", details: "Round face, hazel green eyes, auburn braid", outfit: "Plaid skirt, cardigan, satchel", textures: ["wool knit"] },
    { id: "ch_31", genre: "AD STUDIO", name: "Lab Researcher (F)", details: "40s, sharp features, tight bun", outfit: "High-collared black lab coat", textures: ["authoritative gaze", "metal snaps"] },
    { id: "ch_32", genre: "AD STUDIO", name: "Lab Researcher (M)", details: "Mid 20s, square jaw, dimple", outfit: "Black metal-snap lab coat", textures: ["beaker reflections", "glass"] },
    { id: "ch_33", genre: "AD STUDIO", name: "Rookie Lineman", details: "Early 20s, athletic, USN tattoo", outfit: "High-vis vest, hard hat", textures: ["sweat streaks", "tattoo ink"] },
    { id: "ch_34", genre: "AD STUDIO", name: "Veteran Saturation Diver", details: "50s, barrel-chested, puffy skin", outfit: "Yellow drysuit, brass helmet", textures: ["umbilical cable", "marine snow"] },
    { id: "ch_35", genre: "EDITORIAL LUXURY", name: "Retro Pin-Up Model", details: "Heart face, victory roll hair", outfit: "Polka-dot dress, red belt", textures: ["beauty mark", "victory rolls"] },
    { id: "ch_36", genre: "EDITORIAL LUXURY", name: "Minimalist Editorial Model", details: "Tall, statuesque, shaved head", outfit: "Black wool coat, white silk", textures: ["porcelain skin", "matte silk"] },
    { id: "ch_37", genre: "UGC LIFESTYLE", name: "Bohemian Style Muse", details: "Oval face, freckles, wavy hair", outfit: "Fringed suede, maxi skirt", textures: ["feather earrings", "freckle fidelity"] },
    { id: "ch_38", genre: "EDITORIAL LUXURY", name: "High-Fashion Street Model", details: "Non-binary, platinum cropped hair", outfit: "Neon windbreaker, tech bag", textures: ["nylon sheen", "urban swagger"] },
    { id: "ch_39", genre: "EDITORIAL LUXURY", name: "Runway Plus-Size Icon", details: "Full-figured, statement hoops", outfit: "Geometric silk dress", textures: ["radiant skin", "bold pattern"] },
    { id: "ch_40", genre: "EDITORIAL LUXURY", name: "Avant-Garde Couture Model", details: "Platinum hair, icy eyes", outfit: "Structured gown, metallic accents", textures: ["stiletto heels", "icy gaze"] },
    { id: "ch_41", genre: "EDITORIAL LUXURY", name: "Vintage Runway Star", details: "Auburn curls, emerald eyes", outfit: "Burgundy satin, lace gloves", textures: ["nostalgic grace", "satin luster"] },
    { id: "ch_42", genre: "CYBER STARTUP", name: "Futuristic Techwear Model", details: "Square face, spiky silver hair", outfit: "Neon jacket, AR visor", textures: ["metallic sneakers", "digital glitch"] },
    { id: "ch_43", genre: "EDITORIAL LUXURY", name: "Romantic Editorial Muse", details: "Golden hair, soft features", outfit: "Flowing chiffon, floral crown", textures: ["ethereal softness", "chiffon layers"] },
    { id: "ch_44", genre: "EDITORIAL LUXURY", name: "Urban Chic Model", details: "Sleek bob, sharp cheekbones", outfit: "Leather jacket, ripped jeans", textures: ["oversized sunglasses", "leather grain"] },
    { id: "ch_45", genre: "EDITORIAL LUXURY", name: "Gothic Muse", details: "Pale face, dark kohl eyes", outfit: "Black velvet, silver jewelry", textures: ["platform boots", "velvet depth"] },
    { id: "ch_46", genre: "UGC LIFESTYLE", name: "Aspiring Athlete (Black)", details: "18, square face, muscular", outfit: "State team jersey, sweatband", textures: ["powerful legs", "jersey mesh"] },
    { id: "ch_47", genre: "UGC LIFESTYLE", name: "Aspiring Athlete (Red Hair)", details: "18, Greek nose, wavy hair", outfit: "State team jersey, shorts", textures: ["wavy red hair", "athletic build"] },
    { id: "ch_48", genre: "UGC LIFESTYLE", name: "Aspiring Athlete (Tattooed)", details: "Long face, heart tattoo on arm", outfit: "State team jersey", textures: ["tattoo ink", "Roman nose"] },
    { id: "ch_49", genre: "UGC LIFESTYLE", name: "Artistic Dreamer", details: "Heart face, wavy blonde hair", outfit: "Oversized denim, sketchbook", textures: ["graphite smudges", "denim weave"] },
    { id: "ch_50", genre: "UGC LIFESTYLE", name: "Tech-Savvy Gamer", details: "Asian, spiky dyed hair", outfit: "Neon hoodie, headphones", textures: ["silver nose piercing", "hoodie texture"] },
    { id: "ch_51", genre: "UGC LIFESTYLE", name: "Cheerful Best Friend", details: "Round face, dimples", outfit: "Bright t-shirt, bracelets", textures: ["curly brown hair", "vivacious smile"] },
    { id: "ch_52", genre: "CYBER STARTUP", name: "Rebellious Punk", details: "Spiky red hair, piercings", outfit: "Leather jacket, Fender guitar", textures: ["black lipstick", "studded belt"] },
    { id: "ch_53", genre: "UGC LIFESTYLE", name: "Shy Musician", details: "14, delicate features, bangs", outfit: "Pastel skirt, violin case", textures: ["hyper-realistic hands", "pensive gaze"] },
    { id: "ch_54", genre: "UGC LIFESTYLE", name: "Trendy Influencer", details: "Platinum hair, vivacious", outfit: "Designer jacket, smartphone", textures: ["flashy makeup", "poised stance"] },
    { id: "ch_55", genre: "UGC LIFESTYLE", name: "Outdoors Explorer", details: "16, auburn hair, freckles", outfit: "Hiking boots, compass", textures: ["messy hair", "weathered boots"] },
    { id: "ch_56", genre: "UGC LIFESTYLE", name: "Ballet Club Kid", details: "16, expressiv eyes, curls", outfit: "Black leotard, opaque tights", textures: ["animated gestures", "fabric tension"] },
    { id: "ch_57", genre: "UGC LIFESTYLE", name: "Science Whiz", details: "15, Black, black glasses", outfit: "Lab coat, stickered laptop", textures: ["analytical gaze", "laptop stickers"] },
    { id: "ch_58", genre: "UGC LIFESTYLE", name: "Weather-Beaten Sea Captain", details: "70s, deep wrinkles, mahogany skin", outfit: "Navy pea coat, brass buttons", textures: ["tobacco-stained beard", "salt-crust"] },
    { id: "ch_59", genre: "CYBER STARTUP", name: "Holographic Female Anchor", details: "Symmetrical, digital glitch", outfit: "Formal light-fabric blazer", textures: ["data-blue eyes", "scan-lines"] },
    { id: "ch_60", genre: "AD STUDIO", name: "Hero Product Hand (Male)", details: "Hyper-detailed skin, visible veins", outfit: "High-end watch strap", textures: ["tactile pores", "wrist hair"] }
  ]
};